apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
data:
  config.json: |-
    {
      "nodePathMap": {{ .Values.nodePathMap | toPrettyJson | nindent 8 }}
    }
