name: Update Homebrew Formula Manual Test

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: garden-cli
          tag-name: ${{ github.event.inputs.tag-name }}
          formula-path: Formula/garden-cli.rb
          homebrew-tap: garden-io/homebrew-garden
          base-branch: master
          create-pullrequest: true
          download-url: https://github.com/garden-io/garden/releases/download/${{ github.event.inputs.tag-name }}/garden-${{ github.event.inputs.tag-name }}-macos-amd64.tar.gz
          commit-message: |
            Bump {{formulaName}} to {{version}}.

            For more info: https://github.com/garden-io/garden
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
