name: Update Homebrew Formula (deprecated)

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  homebrew-release:

    runs-on: macOS-latest

    steps:
    - name: Checks if pre-release
      if: github.event.release.prerelease == true
      run: |
        echo This is running against a pre-release.
        echo Skipping all the next steps.
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      if: github.event.release.prerelease != true
    - name: Use Node.js 12.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      if: github.event.release.prerelease != true
      with:
        node-version: 12.x
    - name: Setup git
      if: github.event.release.prerelease != true
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        echo "${{ secrets.DEPLOY_KEY_HOMEBREW_GARDEN }}" > ~/.ssh/homebrew_id
        chmod 600 ~/.ssh/homebrew_id
        ssh-add -K ~/.ssh/homebrew_id
        git config --global user.email "e.libralato@gmail.com"
        git config --global user.name "Github Actions"
        tee -a ~/.ssh/config << END
        Host github.com
            AddKeysToAgent yes
            UseKeychain yes
            IdentityFile ~/.ssh/homebrew_id
        END
    - name: Release Homebrew Formula
      if: github.event.release.prerelease != true
      uses: garden-io/update-homebrew-action@8f5f7e8b9ab33e0ed39851013a9187c2154fd69b
      with:
        packageName: 'garden-cli'
        templatePath: 'support/homebrew-formula.rb'
        tapRepo: 'garden-io/homebrew-garden'
        srcRepo: 'garden-io/garden'
        authToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Test Homebrew package
      if: github.event.release.prerelease != true
      run: |
        echo 'Testing brew install'
        brew tap garden-io/garden
        brew install garden-cli
        echo 'Running garden --version'
        garden --version
